config/routes.rb
ClassMngmt::Application.routes.draw do
  devise_for :students
  resources :students

  namespace :api do
    resources :students
  end

  post '/hello', to: 'welcome#create_hello'

  get '/hello', to: 'welcome#hello'
  get '/hello/:name', to: 'welcome#hello'

  get '/thanks', to: 'welcome#thanks'

  post '/mailbox', to: 'welcome#mailbox'

  root to: 'welcome#hello'

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :registrations
  has_many :students, through: :registrations
  belongs_to :student

  scope :rails, -> { where('title LIKE ?', '%Rails%')}

  scope :small_class, -> {where 'number_of_students < 10'}
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  belongs_to :student
  belongs_to :course
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :registrations
  has_many :courses, through: :registrations

  after_create :notify_admin

  accepts_nested_attributes_for :courses

  #validates_presence_of :full_name, message: 'must be filled in!!'

  validates :full_name, :favorite_ice_cream_flavor, presence: {message: 'must be filled in!!!'}

  validates :email, presence: true, length: { minimum: 6, maximum: 256, message: 'length has to be between 6-256'}
  validates :age, numericality: { only_integer: true }

  # after_validation :clean_up_full_name

  scope :teachers, -> { where profession: 'Teacher' }
  scope :names, -> { pluck :full_name }

  def clean_up_full_name
    self.full_name = "Ice Cream Wrangler Clown"
  end

private
  def notify_admin
    AdminMailer.notify_about_new(self).deliver
  end

end

app/controllers/api/students_controller.rb
class Api::StudentsController < ApiController

  def index
    students = Student.all

    respond_to do |format|
      format.json { render json: students.to_json }
      format.xml  { render xml: students.to_xml }
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  before_filter :check_api_token

  private
  
  def check_api_token
    render json: 'BAD!!', status: :unauthorized unless params[:token] == 'renee'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_title, :set_time

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:full_name, :bio, :age, :favorite_ice_cream_flavor, :profession]
  end

  private

  def set_time
    @time = Time.now
  end

  def set_title
    @title = 'Class App'
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_filter :authenticate_student!

  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
    @title = "Students Page"
    @read_more = params[:read_more]
  end

  # GET /students/1
  # GET /students/1.json
  def show
    render 'show', layout: false
  end

  # GET /students/new
  def new
    @student = Student.new
    @student.courses.build
    render 'new', layout: :default #layout of ApplicationController - parent controller for this one
  end

  # GET /students/1/edit
  def edit
    render 'edit', layout: 'application'
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)
    respond_to do |format|
      if @student.save
        #format.html { render 'shared/thank_you'}
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render action: 'show', status: :created, location: @student }
      else
        format.html { render action: 'new' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:full_name, :age, :bio, :profession, :favorite_ice_cream_flavor, :email, course_ids: [], courses_attributes: [:title])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  layout 'application'

  def hello
    flash[:notice] = "You are looking at my home page!"
    @name = params[:name]
  end

  def create_hello
    render text: "hello world!!"
  end

  def thanks
    render 'shared/thank_you'
  end

  def mailbox
    render 'shared/thank_you'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def devise_links
    if current_student #student_signed_in?
      link_to 'Log Out', destroy_student_session_path, method: :delete
    else
      link_to 'Log In', new_student_session_path
    end
  end

end

app/helpers/students_helper.rb
module StudentsHelper

  def short_bio student
    bio = student.bio.to_s
    if @read_more.to_i == student.id
      read_less = link_to ' Read Less', students_path(read_more: 0)
      bio + read_less
    else
      read_more = link_to 'Read More', students_path(read_more: student.id)
      t = truncate bio, length: 30, omission: '... '
      t.gsub('... ', "... #{read_more}")
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<p><%= link_to 'Home', root_path %><p>
<%= "You are signed in as: #{current_student.full_name}" if current_student %>
<%= devise_links %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClassMngmt</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

<%= render 'shared/footer' %>

</body>
</html>

app/views/layouts/special.html.erb
<html>
<head>
  <title> <%= @title %> </title>
  <%= content_for :head %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
  <%= content_for :something_cool %>
  <%= render 'layouts/header' %>
</body>
</html>

app/views/shared/_footer.html.erb
<p> &copy; Ren&eacute;e Hendricksen <p>

app/views/shared/thank_you.html.erb
Thank you for your submission at <%= @time %>

app/views/students/_extra_fields_for_students.html.erb
  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :profession %><br>
    <%= f.text_field :profession %>
  </div>
  <div class="field">
    <%= f.label :favorite_ice_cream_flavor %><br>
    <%= f.text_field :favorite_ice_cream_flavor %>
  </div>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'extra_fields_for_students', f: f %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

<p><h1> Course Fields </h1>
  <%= f.fields_for :courses do |course_form| %>
    <div class="field">
      <%= course_form.label :title %><br>
      <%= course_form.text_field :title %>
    </div>
  <% end %></p>

    <%= f.collection_select(:course_ids, Course.all, :id, :title, {selected: @student.course_ids, include_blank: false},{ multiple: true }) %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<% content_for :something_cool do %>
  <p> I can put something to render on another view in a certain spot.</p>
<% end %>

<h1>Listing students</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Age</th>
      <th>Bio</th>
      <th>Profession</th>
      <th>Favorite ice cream flavor</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.full_name %></td>
        <td><%= student.age %></td>
        <td><%= raw short_bio student %></td>
        <td><%= student.profession %></td>
        <td><%= student.favorite_ice_cream_flavor %></td>
        <td><%= student.email %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%# This is a comment! %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p>
  <strong>Full name:</strong>
  <%= @student.full_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @student.age %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @student.bio %>
</p>

<p>
  <strong>Profession:</strong>
  <%= @student.profession %>
</p>

<p>
  <strong>Favorite ice cream flavor:</strong>
  <%= @student.favorite_ice_cream_flavor %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/welcome/hello.html.erb
<h1> HELLO WORLD!</h1>
  <%= @time %>
  Your name is: <%= @name %>
<p><%= link_to 'Make your name Bob', hello_path(name: "Bob #{(1..5).to_a.sample}") %></p>
<p><%= link_to 'See all the Students!', students_path %> </p>
<p><%= link_to 'Create a new Student!', new_student_path %></p>